version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: nest_postgres
    restart: always
    environment:
      POSTGRES_USER: ilya
      POSTGRES_PASSWORD: ilya_password
      POSTGRES_DB: twitter_clone
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
